"""Build an offline Atlas review inventory; never infer completed fact checks."""
import argparse
from datetime import date
import json
from pathlib import Path
import re

import yaml

ROOT = Path(__file__).resolve().parents[1]
POLICY = {
    'tools': ('高', '毎月候補', '提供状況・仕様・料金・利用条件'),
    'data': ('高', '毎月候補', '版・対象範囲・利用条件・更新頻度'),
    'methods': ('中', '四半期候補', '適用条件・実装仕様・評価の限界'),
    'concepts': ('低', '年次候補', '定義・出典・断定の範囲'),
    'cases': ('中', '半年候補', '事例時点・効果の根拠・一般化の範囲'),
    'guides': ('中', '四半期候補', '前提環境・実行手順・学習導線'),
}


def source_dates(source):
    # Only explicit source-check dates, not publication dates or front matter.
    section = re.search(r'^## 出典\s*\n(.*?)(?=^## |\Z)', source, re.M | re.S)
    return sorted(set(re.findall(r'(\d{4}-\d{2}-\d{2})(?:再)?確認', section[1]))) if section else []


def render(root=ROOT):
    reviews = json.loads((root / 'editorial/atlas-review-records.json').read_text(encoding='utf-8'))
    pages = sorted((root / 'docs/atlas').rglob('*.md'))
    paths = {p.relative_to(root / 'docs').as_posix() for p in pages}
    if reviews.keys() - paths:
        raise ValueError('Review records reference missing pages')
    rows = []
    for page in pages:
        source = page.read_text(encoding='utf-8')
        match = re.match(r'---\s*\n(.*?)\n---', source, re.S)
        meta = yaml.safe_load(match[1]) if match else {}
        path = page.relative_to(root / 'docs').as_posix()
        record = reviews.get(path, {})
        checked = record.get('reviewed_on')
        if checked:
            date.fromisoformat(checked)
            if not record.get('evidence'):
                raise ValueError(f'{path}: completed review requires evidence')
        category = page.parent.name
        priority, cadence, task = POLICY.get(category, ('中', '毎月候補', '索引・ナビゲーションの一致'))
        dates = source_dates(source)
        span = '〜'.join([dates[0], dates[-1]]) if len(dates) > 1 else (dates[0] if dates else '未抽出')
        limits = re.findall(r'[^。\n]*(?:未確認|未検証|未実施|未了|403)[^。\n]*', source)
        flag = '本文に未確認等の記載あり' if limits else '記載未検出（完了を意味しない）'
        if limits:
            excerpt = re.sub(r'\[([^]]+)\]\([^)]*\)', r'\1', limits[0]).replace('|', '\\|')
            flag += '：' + excerpt[:100] + ('…' if len(excerpt) > 100 else '')
        task = str(record.get('next_action', task)).replace('|', '\\|').replace('\n', ' ')
        title = str(meta.get('title', page.stem)).replace('|', '\\|')
        evidence = str(record.get('evidence', '未記録')).replace('|', '\\|').replace('\n', ' ')
        rows.append(f'| [{title}](../docs/{path}) | {meta.get("updated", "未記載")} | {span} | {checked or "未記録"} | {priority}・{cadence} | {task}／{flag} | {evidence} |')
    return '''# Atlasの確認台帳

<!-- Generated by scripts/build_atlas_review_register.py; edit records, not this table. -->

対象は `docs/atlas/` の全Markdown（索引・移転案内を含む）。出典確認日の範囲は「出典」節にある明示的な日付を機械抽出したもの。本文編集日や公開日を確認日に流用しない。日付のない出典や別の表記は未抽出になり得る。新しい出典が一つあってもページ全体の確認済みを意味しない。

全体点検日は `editorial/atlas-review-records.json` に根拠とともに手動記録する。未記録は未実施の断定ではなく、全体点検の証跡がない状態である。本文の未確認表記も検索の手掛かりに過ぎない。今回は外部出典を一括で再確認していない。

優先度・巡回頻度は分類から決める初期候補。毎月全候補を再確認する義務ではない。月次は5〜10ページを選び、重大変更・料金・利用条件・未確認事項・過去の点検記録を踏まえて調整する。同じページだけを選び続けず、未記録ページも順番に取り上げる。

ページ数：''' + str(len(pages)) + '''。

| ページ | 本文編集日 | 出典確認日の記載範囲 | 全体点検日 | 初期優先度・頻度 | 次に確認する内容 | 全体点検の根拠・残課題 |
| --- | --- | --- | --- | --- | --- | --- |
''' + '\n'.join(rows) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed inventory is stale')
    args = parser.parse_args()
    result = render()
    output = ROOT / 'editorial/atlas-review-register.md'
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != result:
            raise SystemExit('Atlas review register is stale; regenerate it')
        print('Atlas review register: up to date')
    else:
        output.write_text(result, encoding='utf-8')
        print('Updated editorial/atlas-review-register.md')


if __name__ == '__main__':
    main()
